# 4 NumPy Basics: Arrays and  Vectorized Computation

In [78]:
import numpy as np

## 4.1 The NumPy ndarray: A Multidimensional Array Object

In [69]:
data=np.array([[1.3,3.4,2.2],[6.0,4.5,7.6]])
data

array([[1.3, 3.4, 2.2],
       [6. , 4.5, 7.6]])

Data shape returns (number of rows, number of columns)

In [70]:
data.shape


(2, 3)

Arrays behave exactly as you would expect under the basic operations

In [71]:
data+data


array([[ 2.6,  6.8,  4.4],
       [12. ,  9. , 15.2]])

In [72]:
3*data

array([[ 3.9, 10.2,  6.6],
       [18. , 13.5, 22.8]])

In [73]:
data.dtype

dtype('float64')

In [74]:
data1=[3.4,4.5,5.6,6.7]

In [75]:
arr1=np.array(data1)

In [76]:
arr1

array([3.4, 4.5, 5.6, 6.7])

In [77]:
data.ndim

2

ndim tells you the number of indices in the "tensor"

In [24]:
arr1.ndim

1

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
my_arr1=np.arange(1_000_000)

In [27]:
my_list1=list(range(1_000_000))

An example of how much faster np.array is than standard python lists. Notice the Jupiter magic commands starting with %

In [33]:
%timeit my_arr=my_arr1*3

272 μs ± 1.37 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [36]:
%timeit my_list2=[x*3 for x in my_list1]

22.1 ms ± 177 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
np.zeros_like(data)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)

In [45]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [47]:
my_arr1>my_arr

array([False, False, False, ..., False, False, False], shape=(1000000,))

In [48]:
arr=np.arange(15)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
arr[3:6]

array([3, 4, 5])

In [51]:
arr[4:6]=90

In [52]:
arr

array([ 0,  1,  2,  3, 90, 90,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
arr2d=np.arange(10,10)

In [54]:
arr2d

array([], dtype=int64)

In [55]:
arr2d.shape

(0,)

In [56]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
arr2d.ndim

2

In [61]:
arr2d[2]=23

In [62]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 23, 23]])

In [65]:
arr2d[0,2]

np.int64(3)

In [66]:
int(arr2d[0,2])

3

In [68]:
arr2d[:1,:2]

array([[1, 2]])

An interesting way of indexing is by using arrays of booleans

In [79]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [80]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [83]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

Only the entries corresponding to True will be returned

In [84]:
data[names=='Bob']

array([[4, 7],
       [0, 0]])

You can really use the boolean indexing as if it was a canonical way od indexing

In [85]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [86]:
data[names == "Bob", 1]

array([7, 0])

In [87]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [88]:
mask = (names == "Bob") | (names == "Will")

In [89]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

**NOTE**: Selecting data from an array by Boolean indexing and assigning the result to a new variable always creates a copy of the data, even if the returned array is unchanged.

You can also assign values using booleans

In [90]:
data[data < 0] = 0

In [91]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [92]:
data[names != "Joe"] = 7

In [93]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

There is also *fancy indexing*, namely indexing using arrinteger arrays (or lists)

In [94]:
arr = np.arange(32).reshape((8, 4))

In [95]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [96]:
arr[[4, 3, 0, 6]]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [24, 25, 26, 27]])

In [97]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Fancy indexing in this case is taking each row and mixing the columns according to the order in the second list.

In [98]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

You can transpose matrices with .T

In [99]:
arr1 = np.arange(15).reshape((3, 5))

In [100]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [101]:
arr1.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

You can do the inner product using np.dot or with the operator @

In [102]:
np.dot(arr1.T,arr1)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [104]:
arr1.T@arr1

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

You can swap a particular pair of indices using swapaxes (in this case we only have 2 so it is like transposing)

In [105]:
arr1.swapaxes(0, 1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## 4.2 Pseudorandom Number Generation